import type { ReactNode } from 'react'; import type { Viz } from '../data/portfolio'
const Frame=({label,children}:{label:string;children:ReactNode})=><div className="flex aspect-[16/8] w-full flex-col gap-3 border border-white/10 bg-deep p-4" role="img" aria-label={`${label} concept interface preview`}><div className="flex gap-2">{[0,1,2].map(i=><span key={i} className="h-2 w-2 rounded-full bg-white/20"/>)}</div><div className="min-h-0 flex-1">{children}</div></div>
export default function Mockup({viz,bars,label}:{viz:Viz;bars:number[];label:string}){
let v:ReactNode
if(viz==='chat')v=<div className="grid h-full grid-cols-[2fr_1fr] gap-3"><div className="flex flex-col justify-end gap-2">{[70,45,85,55].map((w,i)=><div key={i} className={`h-4 ${i%2?'self-end bg-cyan/70':'bg-white/10'}`} style={{width:`${w}%`}}/>)}</div><div className="flex items-end gap-1 border border-white/10 p-2">{bars.slice(0,5).map((b,i)=><div key={i} className="flex-1 bg-violet/60" style={{height:`${b}%`}}/>)}</div></div>
else if(viz==='line'){const n=bars.length,pts=bars.map((b,i)=>`${(i/(n-1))*200},${60-b*.55}`).join(' ');v=<div className="flex h-full flex-col gap-3"><div className="grid grid-cols-3 gap-2">{[0,1,2].map(i=><div key={i} className="border border-white/10 p-2"><div className="h-1.5 w-1/2 bg-white/20"/><div className={`mt-2 h-3 w-3/4 ${i===2?'bg-cyan':'bg-violet/60'}`}/></div>)}</div><svg viewBox="0 0 200 60" preserveAspectRatio="none" className="min-h-0 flex-1 border border-white/10" aria-hidden><polyline points={pts} className="fill-none stroke-cyan" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/><polyline points={`0,60 ${pts} 200,60`} className="fill-violet/20 stroke-none"/></svg></div>}
else if(viz==='shop')v=<div className="grid h-full grid-cols-3 grid-rows-2 gap-2">{[0,1,2,3,4,5].map(i=><div key={i} className={`flex flex-col justify-between border p-2 ${i===1?'border-cyan/60':'border-white/10'}`}><div className="h-full bg-white/5"/><div className="mt-2 h-1.5 w-2/3 bg-white/20"/><div className={`mt-1 h-1.5 w-1/3 ${i===1?'bg-cyan':'bg-violet/60'}`}/></div>)}</div>
else if(viz==='table')v=<div className="flex h-full flex-col justify-between">{bars.slice(0,5).map((b,i)=><div key={i} className="flex items-center gap-3 border-b border-white/10 pb-1.5"><span className="h-4 w-4 rounded-full bg-white/15"/><span className="h-1.5 w-1/4 bg-white/20"/><span className="ml-auto h-1.5 w-1/3 bg-white/10"><span className="block h-full bg-cyan" style={{width:`${b}%`}}/></span></div>)}</div>
else if(viz==='calendar'){const hl=new Set(bars.map((b,i)=>i*4+(b%4)));v=<div className="grid h-full grid-cols-7 grid-rows-4 gap-1">{Array.from({length:28},(_,i)=><div key={i} className={`${hl.has(i)?(i%3?'bg-violet/60':'bg-cyan'):'bg-white/5'}`}/>)}</div>}
else v=<svg viewBox="0 0 300 100" className="h-full w-full" aria-hidden><g className="stroke-white/30" strokeWidth="1.5" fill="none"><path d="M60 50H100M160 50H200M160 50L200 20M160 50L200 80M260 20L240 20M260 80L240 80"/></g>{[[10,35],[100,35],[200,5],[200,65],[100,70]].map(([x,y],i)=><rect key={i} x={x} y={y} width="50" height="30" rx="2" className={i===2?'fill-cyan':'fill-violet/50'}/>)}<rect x="250" y="35" width="40" height="30" rx="2" className="fill-white/15"/></svg>
return <Frame label={label}>{v}</Frame>}
