import { lazy, Suspense } from 'react'; import { Routes, Route, Navigate } from 'react-router-dom'
import ErrorBoundary from './components/ErrorBoundary'; import { useLocation } from 'react-router-dom'; import ScrollProgress from './components/ScrollProgress'; import Cursor from './components/Cursor'; import Loader from './components/Loader'; import PageTransition from './components/PageTransition'
import Navbar from './components/Navbar'; import Footer from './components/Footer'
const Home=lazy(()=>import('./pages/Home')), Services=lazy(()=>import('./pages/Services')), About=lazy(()=>import('./pages/About')),
Blog=lazy(()=>import('./pages/Blog')), BlogPost=lazy(()=>import('./pages/BlogPost')), Products=lazy(()=>import('./pages/Products')), ProductDetail=lazy(()=>import('./pages/ProductDetail')), Privacy=lazy(()=>import('./pages/Privacy')), Contact=lazy(()=>import('./pages/Contact')), Admin=lazy(()=>import('./pages/Admin')), NotFound=lazy(()=>import('./pages/NotFound'))
export default function App(){const {pathname}=useLocation();return(<><Loader/><ScrollProgress/><Cursor/><PageTransition/><Navbar/><ErrorBoundary key={pathname}><Suspense fallback={<div className="min-h-screen"/>}><main><Routes>
<Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/about" element={<About/>}/>
<Route path="/products" element={<Products/>}/><Route path="/products/:slug" element={<ProductDetail/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="/portfolio" element={<Navigate to="/products" replace/>}/><Route path="/blog" element={<Blog/>}/><Route path="/blog/:slug" element={<BlogPost/>}/><Route path="/contact" element={<Contact/>}/><Route path="/portfolio/:slug" element={<Navigate to="/products" replace/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<NotFound/>}/>
</Routes></main></Suspense></ErrorBoundary><Footer/>
<a href="https://wa.me/923106370125" aria-label="Chat on WhatsApp" title="Chat with us on WhatsApp" className="fixed bottom-5 right-5 z-40 rounded-full bg-cyan px-4 py-3 text-sm font-medium text-ink">WhatsApp</a></>)}
